name: actions-practice
on: push
jobs:
  testing-env-vars:
    name: Testing Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Environment variables
        env:
          NAME: Luffy
        run: |
          echo "Hello ${{ env.NAME }}"
          echo "${{ env.NAME }} eats chicken"
