name: actions-practice
on: push
jobs:
  testing-env-vars:
    name: Testing Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Environment variables
        env: 
          NAME: Luffy
        run: |
          echo "Hello ${{ toJson(vars) }}"
          echo "This is a mock secret: ${{ secrets.TEST_PASSWORD }}"
  file-creation:
    name: File creation
    runs-on: ubuntu-latest
    steps:
      - name: Creation
        run: |
          echo "Hello from file-creation job" > greeting.txt
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: text-file
          path: ./greeting.txt
  read-file:
    name: Read
    needs: file-creation
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: text-file
      - name: Read file
        run: cat greeting.txt

  

